---
- name: install docker
  hosts: sql
  tasks:
    - name: установка основных репозиторий 
      block:
        - name:
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
            update-cache: true

        - name: установка доп пакетов
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: true

        - name: Pause for 100 sec
          ansible.builtin.pause:
            seconds: 100
        - name: создание папки для ключа докер
          file: 
            path: /etc/apt/keyrings
            state: directory

        - name: установка ключа
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
            keyring: /etc/apt/keyrings/docker.gpg

        - name: установка стаб репо
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
              https://download.docker.com/linux/ubuntu
              {{ ansible_distribution_release }} stable
            state: present
            update-cache: true

        - name: Pause for 100 sec
          ansible.builtin.pause:
            seconds: 100


        - name: install docker-ce
          apt: 
            name:
              - docker-ce
              - docker-ce-cli
              - python3-docker
              - containerd.io
              - docker-compose-plugin
            update-cache: true

        - name: Pause for 30 sec 
          ansible.builtin.pause:
            seconds: 30

        - name: start docker
          systemd:
            name: docker
            state: restarted
        - name: Pause for 30 sec
          ansible.builtin.pause:
            seconds: 30
      become: true
    
    - name: внесене пользователя в группу докер
      block:
        - name:
          user:
            name: "vova"
            group: docker
            append: true
    - name: install docker-compose
      block:
        - name: install docker
          get_url:
            url: https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-linux-x86_64
            dest: /usr/local/bin/docker-compose
            mode: 0755
        
        - name: install
          apt:
            name: docker-compose
        - name: Pause for 30 sec
          ansible.builtin.pause:
            seconds: 30
    - name: 
      reboot:
    - name: Pause for 100 sec
      ansible.builtin.pause:
        seconds: 100
  become: true
