---
- name: install kafka
  hosts: kafka
  tasks:
    - name: установка основных репозиторий 
      block:
        - name:
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
            update-cache: true
        - name: Pause 60 sec
          ansible.builtin.pause:
            seconds: 60         
        
        - name: установка доп пакетов
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
              - tar
              - wget
              - default-jdk
            update-cache: true
        - name: Pause for 100 sec
          ansible.builtin.pause:
            seconds: 100

        - name: создание папки для ключа elasticsearch
          file: 
            path: /etc/apt/keyrings
            state: directory

        - name: установка ключа elasticsearch
          apt_key:
            url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
            state: present
            keyring: /etc/apt/keyrings/elasticsearch.gpg

        - name: установка стаб репо elasticsearch
          apt_repository:
            repo: >
              deb [arch=amd64 signed-by=/etc/apt/keyrings/elasticsearch.gpg]
              https://artifacts.elastic.co/packages/7.x/apt stable main
            state: present



        - name: Pause for 100 sec
          ansible.builtin.pause:
            seconds: 200
            
        - name: install elasticsearch
          apt: 
            name:
              - install elasticsearch
            update-cache: true
          become: true

        - name: Pause for 50 sec
          ansible.builtin.pause:
            seconds: 50
      become: true
