---
- name: install kafka
  hosts: kafka
  tasks:
    - name: установка основных репозиторий 
      block:
        - name:
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
            update-cache: true
        - name: Pause 60 sec
          ansible.builtin.pause:
            seconds: 60         
        
        - name: установка доп пакетов
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
              - tar
              - wget
              - default-jdk
            update-cache: true
        - name: Pause for 100 sec
          ansible.builtin.pause:
            seconds: 100
        
        - name: проверка версии 
          shell: |
            java -version
          args:
            warn: no
        - name: Pause for 10 sec
          ansible.builtin.pause:
            seconds: 10

        - name: скачаем репо kafka
          shell: |
            rm -Rfv /opt/kafka
            rm -Rfv /home/vova/tar
            mkdir /home/vova/tar
            wget -P /home/vova/tar/ https://downloads.apache.org/kafka/3.5.1/kafka_2.13-3.5.1.tgz                                    
            mkdir /opt/kafka
          args:
            warn: no
        - name: Pause for 30 sec
          ansible.builtin.pause:
            seconds: 30


        - name: распаковка репо kafka
          shell: |
            tar zxf /home/vova/tar/kafka_*.tgz -C /opt/kafka --strip 1
          args:
            warn: no       

        - name: создаем файлы папки юнита
          shell: |
            rm -Rfv /etc/systemd/system/zookeeper.service
            rm -Rfv /etc/systemd/system/kafka.service
            touch /etc/systemd/system/zookeeper.service
            touch /etc/systemd/system/kafka.service
          args:
            warn: no

        - name: создать пользователя kafka
          user:
            name: kafka
            state: present  

        - name: внести изменение в файл конфигурации kafka  чтоб можно было вручную удлять топик + создаем учетку kafka
          shell: |
            echo "delete.topic.enable = true" >> /opt/kafka/config/server.properties
            chown -R kafka:kafka /opt/kafka
          args:
            warn: no
        - name: Pause for 10 sec
          ansible.builtin.pause:
            seconds: 10

        - name: создаем файлы конфигурации юнита
          shell: |
            echo  "[Unit]
                \nDescription=Zookeeper Service \
                \nRequires=network.target remote-fs.target \
                \nAfter=network.target remote-fs.target \
                \n
                \n[Service] \
                \nType=simple \
                \nUser=kafka \
                \nExecStart=/opt/kafka/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties \
                \nExecStop=/opt/kafka/bin/zookeeper-server-stop.sh \
                \nExecReload=/bin/kill -HUP $MAINPID \
                \nRestart=on-failure \
                \n
                \n[Install] \
                \nWantedBy=multi-user.target" > /etc/systemd/system/zookeeper.service
          args:
            warn: no   
        - name: создаем файлы конфигурации юнита
          shell: |
            echo "[Unit]
                  \nDescription=Kafka Service \
                  \nRequires=zookeeper.service \
                  \nAfter=zookeeper.service \
                  \n
                  \n[Service] \
                  \nType=simple \
                  \nUser=kafka \
                  \nExecStart=/bin/sh -c '/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties > /opt/kafka/kafka.log 2>&1' \
                  \nExecStop=/opt/kafka/bin/kafka-server-stop.sh \
                  \nExecReload=/bin/kill -HUP $MAINPID \
                  \nRestart=on-failure \
                  \n
                  \n[Install] \
                  \nWantedBy=multi-user.target" >> /etc/systemd/system/kafka.service            
          args:
            warn: no
        - name: Pause for 5 sec
          ansible.builtin.pause:
            seconds: 5

        - name: перезагрузка демона
          shell: |
            systemctl daemon-reload
            systemctl enable zookeeper kafka
          args:
            warn: no
        - name: Pause for 20 sec
          ansible.builtin.pause:
            seconds: 20

        - name: перезагрузка сервиса
          systemd:
            name: kafka
            state: started
        - name: Pause for 20 sec
          ansible.builtin.pause:
            seconds: 20

        - name: проверка соединения
          shell: |
            ss -tunlp | grep :9092
          args:
            warn: no

