---
- name: install elk
  hosts: elk
  tasks:
    - name: установка основных репозиторий 
      block:
        - name:
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
            update-cache: true
        - name: Pause 60 sec
          ansible.builtin.pause:
            seconds: 60         
        
        - name: установка доп пакетов
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
              - tar
              - wget
              - default-jdk
              - apt-transport-https
            update-cache: true
        - name: Pause for 100 sec
          ansible.builtin.pause:
            seconds: 100

        - name: установка эластика
          shell: |
            wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
            dpkg --configure -a
            apt-get -y --fix-broken install
            apt-get -y update
            apt-get install elasticsearch 
          args:
            warn: no 
            
        - name: Pause for 50 sec
          ansible.builtin.pause:
            seconds: 50

      become: true

- name: elk1 изменение файла elasticsearch.yml
  hosts: elk1
  tasks:
    - name: elk1 
      ansible.builtin.copy:
        src: /home/vova/project/git_project/ansible-playbooks-install/elk/prop.elastic-node1
        dest: /etc/elasticsearch/elasticsearch.yml
        follow: yes
  become: true


- name: elk2 изменение файла elasticsearch.yml
  hosts: elk2
  tasks:
    - name: elk2
      ansible.builtin.copy:
        src: /home/vova/project/git_project/ansible-playbooks-install/elk/prop.elastic-node2
        dest: /etc/elasticsearch/elasticsearch.yml
        follow: yes
  become: true      

- name: elk3 изменение файла elasticsearch.yml
  hosts: elk3
  tasks:    
    - name: elk3
      ansible.builtin.copy:
        src: /home/vova/project/git_project/ansible-playbooks-install/elk/prop.elastic-node3
        dest: /etc/elasticsearch/elasticsearch.yml
        follow: yes
  become: true      

- name: elk1 запуск elk1
  hosts: elk1
  tasks:
    - name: запуск кластера elk1
      shell: |
        sudo systemctl start elasticsearch.service 
      args:
        warn: no

    - name: Pause for 50 sec
      ansible.builtin.pause:
        seconds: 50
    - name: проверка кластера
      shell: |
        curl -X GET "http://localhost:9200/_cluster/health?pretty"
      args:
        warn: no
  become: true

- name: elk2
  hosts: elk2
  tasks:
    - name: elk2
      shell: |
        sudo systemctl start elasticsearch.service
      args:
        warn: no

- name: elk3
  hosts: elk3
  tasks:
    - name:  elk3
      shell: |
        sudo systemctl start elasticsearch.service
      args:
        warn: no
