---
- name: install elk
  hosts: elk
  tasks:
    - name: установка основных репозиторий 
      block:
        - name:
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present
            update-cache: true
        - name: Pause 60 sec
          ansible.builtin.pause:
            seconds: 60         
        
        - name: установка доп пакетов
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
              - tar
              - wget
              - default-jdk
              - apt-transport-https
            update-cache: true
        - name: Pause for 100 sec
          ansible.builtin.pause:
            seconds: 100

        - name: установка эластика
          shell: |
            wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
            dpkg --configure -a
            apt-get -y --fix-broken install
            apt-get -y update
            apt-get install elasticsearch 
          args:
            warn: no
            
        - name: Pause for 50 sec
          ansible.builtin.pause:
            seconds: 50
      become: true
